import re
import string
from fpdf import FPDF

def clean_text(text):
    """Cleans text for NLP processing."""
    text = str(text).lower()
    text = re.sub(r'http\S+\s*', ' ', text)
    text = re.sub(r'RT|cc', ' ', text)
    text = re.sub(r'#\S+', '', text)
    text = re.sub(r'@\S+', ' ', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'[^\x00-\x7f]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def get_keywords(text):
    """Extracts meaningful keywords, filtering out common 'noise' words."""
    # Words to ignore (Filtering noise)
    stop_words = {'into', 'type', 'required', 'and', 'the', 'for', 'from', 'with', 'this', 'that', 'our', 'your'}
    words = set(re.findall(r'\b\w{3,}\b', text.lower()))
    return words - stop_words

def create_pdf_report(score, matched, missing):
    """Generates a structured and professional PDF report."""
    pdf = FPDF()
    pdf.add_page()
    
    # --- Page Border ---
    pdf.rect(5, 5, 200, 287) # Adds a nice outer border

    # --- Title Section ---
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(0, 51, 102) # Dark Blue
    pdf.cell(200, 20, "RESUME ANALYSIS REPORT", ln=True, align='C')
    
    # --- Match Score Section ---
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0) # Black
    pdf.cell(50, 10, "Overall Match Score:", ln=False)
    
    # Color coding the score
    if score >= 70:
        pdf.set_text_color(0, 128, 0) # Green
    else:
        pdf.set_text_color(255, 0, 0) # Red
    pdf.cell(50, 10, f"{score}%", ln=True)
    
    pdf.set_text_color(0, 0, 0) # Reset to Black
    pdf.line(10, 50, 200, 50) # Horizontal line

    # --- Matched Keywords ---
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "1. Key Strengths (Matched Keywords)", ln=True)
    pdf.set_font("Arial", size=10)
    # Join matched keywords and limit to 20 for precision
    matched_str = ", ".join(list(matched)[:20])
    pdf.multi_cell(0, 8, matched_str)

    # --- Missing Skills (Skill Gap) ---
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "2. Skill Gap (Keywords to Add)", ln=True)
    pdf.set_font("Arial", size=10)
    # Filter out common noise and limit to top missing technical terms
    missing_str = ", ".join(list(missing)[:20])
    pdf.multi_cell(0, 8, missing_str)

    # --- Recommendations ---
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(200, 10, "3. Recommendations", ln=True)
    pdf.set_font("Arial", size=10)
    
    if score < 70:
        recommendation = "Low match score. We recommend updating your resume with the missing keywords found in Section 2 to align better with the Job Description."
    else:
        recommendation = "Strong match score. Ensure your experience descriptions highlight the quantified impact of the matched skills in Section 1."
    
    pdf.multi_cell(0, 8, recommendation)

    # --- Footer ---
    pdf.set_y(-25)
    pdf.set_font("Arial", 'I', 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, "Generated by AI Resume Analyzer - Project 2026", align='C')

    return pdf.output(dest='S').encode('latin-1')